# .github/workflows/convert-to-pdf.yml

name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main   
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'doc/**.md'
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:   
  
jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository    
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Build Documentation PDFs
        uses: baileyjm02/markdown-to-pdf@v1.2.0
        with:
          input_dir: doc
          output_dir: pdf
          build_html: false
      
      - name: Add and Commit Changes 
        uses: EndBug/add-and-commit@v9.0.1
        with:
          message: 'Update PDFs'