name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:      

jobs:
  makepdfs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: mkrakowitzer/actions-makepdfs@master
      if: github.ref == 'refs/heads/master'
      with:
        markdown_dir: doc
        output_dir: tmp
    - uses: actions/upload-artifact@v1
      with:
        name: platform-architecture-docs
        path: tmp