name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:      

jobs:
  converttopdf:
    name: Markdown to PDF
    uses: valtyr/pandoc-action@v0.1-alpha

